### ISSUE TITLE
Build Task not visible on TFS 2015 Update 4 even after successful install from marketplace

### ISSUE THREAD

**Issue by aarlaud** [jessehouwing/vsts-snyk-task#10]
Hey Jesse,

I think I read there might be a tweak to the task.json needed, but if installed from the marketplace, where would that be? Or any reason why it wouldn't show as part of the default collection even though it was installed from marketplace and added into it?

let me know if you have any clue to help me troubleshoot this.
thanks !
Antoine

**Comment by jessehouwing** [comment]
It should 'just work'. But I've received the same bug report through multiple channels.

I've pinged vsointegration and vsomarketplace for help.

**Comment by aarlaud** [comment]
Thanks!

On Aug 16, 2018 7:25 AM, Jesse Houwing <notifications@github.com> wrote:

It should 'just work'. But I've received the same bug report through multiple channels.

I've pinged vsointegration and vsomarketplace for help.

**Comment by jessehouwing** [comment]
My sources mention:

> One thing we've seen is ensure the job agent service is running or restart it.   Outside of that, look in event log for errors and escalate to the VSTS team.  For that though, you would need to get that customer to work with us to figure out what's going on.

If you have access to the machine/account, I can get you into contact with them to see what's going on.

**Comment by aarlaud** [comment]
It's not for me. Let me relay that and we'll see what we can get. thanks!

**Comment by jessehouwing** [comment]
Uninstall/reinstall or disable/enable may help.
Restarting the tfs job agent service on the server may help.

But it's likely a server thing and has very little to do with the tasks.

**Comment by aarlaud** [comment]
cool, thanks !
