### ISSUE TITLE
Scanning Solution files

### ISSUE THREAD

**Issue by DarrenSmallwood** [jessehouwing/vsts-snyk-task#11]
Is it possible to scan solution files (.sln), to find all packages.config files, using this vsts task like you can with the CLI?

If so, can you advise how this is done?

**Comment by jessehouwing** [comment]
Probably, the task just calls the commandline client, but if this is a
recent addition to the cli I may have add functionality for this feature.

**Comment by DarrenSmallwood** [comment]
Thank you,i've got it working with the cli so will continue to play around with the task and see what I can do.

Not sure if it's a recent addition or not but the syntax is the same.

**Comment by DarrenSmallwood** [comment]
Ok, so it seems like the problem here is that I can't select a solution file type from the 'File' dropdown. Is this something that can be changed?

Passing the following command into cmd on the build server works successfully but I can't set the file type through the task:

`c:\agent\_work\_tasks\SnykTask_970cf26e-82d3-41c0-be98-b891bac62eb4\1.1.12\node_modules\.bin>snyk.cmd test --file="C:\agent\_work\3\s\ProjectFolder\TestSolution.sln"`

**Comment by jessehouwing** [comment]
Anything can be changed :).

**Comment by DarrenSmallwood** [comment]
Perfect - I just cloned the repo to make the change myself then realised that this is more than simply adding a new option to the picklist as the solution files won't be a fixed name unlike the other files.

Any ideas?

**Comment by jessehouwing** [comment]
File path could simply take the full path...

**Comment by jessehouwing** [comment]
It's also relatively easy to show another input box, but I think it would be enough to just take the existing path picker and select the full file.

**Comment by jessehouwing** [comment]
Looking at the code a extra input box with 'visibleRule' should do the trick, if you have the bandwidth to create a pull request I'd be very happy to merge it.

**Comment by DarrenSmallwood** [comment]
Ok, thanks for your help. Will try each of your solutions over the weekend and see if I can get it working. 

I will create a pull request if necessary.

**Comment by jessehouwing** [comment]
Wonderful much appreciated.

Examples of showing options dynamically in the Ui can be found here:

https://github.com/jessehouwing/vsts-variable-tasks/blob/master/vsts-variable-transform/task.json

**Comment by jessehouwing** [comment]
Setting the file to "default" and then adding in `--file=path/to/solution` in the Additional Arguments may do the trick.

**Comment by jessehouwing** [comment]
Working on a new version which makes the "Files to Scan" dropdown editable.

**Comment by jessehouwing** [comment]
Merging with #12
