### ISSUE TITLE
Monitor branch names requires "refs/heads/" for git branches

### ISSUE THREAD

**Issue by mweinand** [jessehouwing/vsts-snyk-task#18]
The plugin is using `Build.SourceBranch` for matching the monitor branch names and not `Build.SourceBranchName`.  This means for git branches you need to include the `/refs/heads` syntax for the full branch name for the matching to work.  In a few of the examples in the docs just `master` is listed, but this won't work.  You need to use `/refs/heads/master`.  

I think either the plugin should change which variable it is using or the documentation should be updated to be more clear.  Would be happy to help with either option.

**Comment by mweinand** [comment]
I now see that the wiki makes the `Build.SourceBranch` usage clear (with a link even), but the examples still use the basic `master` naming.

**Comment by jessehouwing** [comment]
My recommendation is to use the new Conditions that were introduced in TFS 2017u2. Since this task also supports TFS 2015 to TFS 2017u1, I haven't removed the Branch filter from the task.

The `refs/heads` prefix is dependent on what Git provider you're hooked up to, for GitHub it's just `master`.

**Comment by jessehouwing** [comment]
![image](https://user-images.githubusercontent.com/4173387/55832812-a6f51b00-5b16-11e9-96a9-5c770e72e8e0.png)

**Comment by jessehouwing** [comment]
For YAML syntax see: https://docs.microsoft.com/en-us/azure/devops/pipelines/process/conditions?view=azure-devops&tabs=yaml

**Comment by mweinand** [comment]
Great, this is what we actually switched to for other reasons.  Makes sense not to re-implement on your end.
