### ISSUE TITLE
The organization name doesn't get taken into account

### ISSUE THREAD

**Issue by aarlaud** [jessehouwing/vsts-snyk-task#8]
Specifying the org in the corresponding field is not taken into account.
Looking into the command passed, I see:
......bin\snyk.cmd test "--org=""aarlaud-snyk-demo""" "--file=.......

I think all these quotes make the command confused because in the end I see
Organisation: aarlaud-snyk-dev
2018-03-30T08:30:43.9617477Z Package manager: nuget

Probably a quick simple fix, I'll take a look at the code.

**Comment by jessehouwing** [comment]
I'd really appreciate that :)

**Comment by jessehouwing** [comment]
I suspect simply stripping the "extra quotes" in this line would fix it:
https://github.com/jessehouwing/vsts-snyk-task/blob/master/vsts-snyk/vsts-snyk.ts#L174

This must have been a change in the way the vsts-task-lib is handling arguments when calling executables.

This may be impacting other parameters as well...

**Comment by jessehouwing** [comment]
If you can share a VSTS account name I can share the test version with that account.

**Comment by aarlaud** [comment]
aarlaud@hotmail.com / github-stats.visualstudio.com should work.
thx for that!

**Comment by jessehouwing** [comment]
Shared: https://marketplace.visualstudio.com/items?itemName=jessehouwing.vsts-snyk-DEV
