### ISSUE TITLE
The Continue on Error doesn't allow monitor to run if test fails

### ISSUE THREAD

**Issue by aarlaud** [jessehouwing/vsts-snyk-task#9]
The advanced option "Continue on Error" doesn't apply on the behavior to run Snyk Monitor if Snyk test fails.
I realize that might be more about tasks, "run following tasks if that one fails". I believe the "fail the build" being unchecked allows monitor to run, but I'd suggest to add some details in a contextual help or something indicating the behavior a bit better. Or have a dedicated option running monitor regardless.

Thoughts?

**Comment by jessehouwing** [comment]
The Conditional stuff is added by Visual Studio and indeed controls flow of the tasks, but is not something that is available to the tasks themselves. Unfortunately, that's also an area where I can't add additional documentation.

Does it make sense to call `Snyk Monitor` if test already failed? With the build set to fail, that version should never be able to reach a higher environment... I'm seeing monitor as a way to get notified of issues with code that has passed the CI stage.

**Comment by aarlaud** [comment]
Some folks like to have the results in the UI as well, which doesn't get populated unless you are doing monitor, so it's a bit a question on our end. I'll ask the team what they think. Otherwise you need to uncheck 'fail build' which I'm not super comfortable doing all the time... I'll revert back next week.

**Comment by jessehouwing** [comment]
They can always include a second snyk task with just Monitor turned on and "always run" enabled.

**Comment by jessehouwing** [comment]
But it wouldn't be hard to make this work. right now I'm throwing an exception on `test` failure, instead, I could call `tl.setResult` to set the tasks end-result to failure without aborting. Basically replacing the last few lines in the task with:

```
    if (snykResult === 1 && !settings.failBuild && command === "test") {
        tl.setResult(tl.TaskResult.SucceededWithIssues, "Snyk reported one or more issues. Ignoring due to 'Fail Build = false'.");
    }
    else if (snykResult !== 0) {
        tl.setResult(tl.TaskResult.Failed, `Failed: ${command}: ${snykResult}`);
    }
```

**Comment by jessehouwing** [comment]
https://github.com/jessehouwing/vsts-snyk-task/tree/features/orgfix

**Comment by jessehouwing** [comment]
If you can share a VSTS account name I can share the test version with that account.

**Comment by aarlaud** [comment]
aarlaud@hotmail.com / github-stats.visualstudio.com

thanks again for your awesome help here and on other topics! we really appreciate and value your feedback and assistance.

**Comment by jessehouwing** [comment]
You're welcome. Thanks for taking hte feedback seriously and helping me ensure people get the most out of your tool through my extension.
